#! /bin/bash
set -euo pipefail

readonly relative_script_dir=$(dirname "${BASH_SOURCE[0]}")
readonly script_dir=$(cd "${relative_script_dir}" >/dev/null 2>&1 && pwd)


function cmd_cpp() {
    "${script_dir}/cpp/run.sh" "${@}"
}

function cmd_build() {
    "${script_dir}/cpp/conan/build.sh" "${@}"
}

function cmd_cget() {
    "${script_dir}"/cpp/cget/cget.sh "${@}"
}

function cmd_clean() {
    if [ -d "output" ]; then
       rm -r output
    fi
}

function cmd_conan() {
    "${script_dir}/cpp/conan/conan.sh" "${@}"
}

function cmd_format() {
    "${script_dir}/cpp/clang-format/run.sh" "${@}"
    "${script_dir}/cpp/cmake-format/run.sh" "${@}"
}

function cmd_generate() {
    local sha=$(cd "${script_dir}" > /dev/null 2>&1 && git rev-parse HEAD)
    CI_LAND_SHA="${sha}" PYTHONPATH="${script_dir}" python "${script_dir}"/cil_format.py "${@}"
}

function cmd_profiles() {
    local profiles=($(ls "${script_dir}/cpp/conan/profiles"))
    echo "Profiles:"
    for profile in "${profiles[@]}"
    do
        echo "    ${profile}"
    done
    echo ""
}

function cmd_run() {
    "${script_dir}/cpp/conan/run.sh" "${@}"
}

function cmd_package() {
    $"{script_dir}/cpp/conan/package.sh" "${@}"
}

function cmd_splash() {
    cat "${script_dir}/splash.txt"
}

function cmd_test() {
    "${script_dir}/cpp/conan/test.sh" "${@}"
}

function cmd_vcpkg() {
    "${script_dir}/cpp/vcpkg/vcpkg.sh" "${@}"
}

function show_help() {
    echo "Usage: ${0} [command]"
    echo "
    Commands:
          profiles    - Show list of Conan profiles
          build       - Builds C++ stuff (call run first)
          cget        - Runs cget commands
          clean       - Clean up output directory
          conan       - Runs conan commands
          format      - Formats code
          generate    - Generates common CI configs
          package     - Runs package script
          run         - Installs and builds C++ stuff
          splash      - Really important picture with a bird
          test        - Run ctests in build directory
    "
}

if [ $# -lt 1 ]; then
    cmd_splash
    show_help
    exit 1
fi

readonly cmd="${1}"
shift 1;

case "${cmd}" in
    "build" ) cmd_build $@ ;;
    "cget" ) cmd_cget $@ ;;
    "clean" ) cmd_clean $@ ;;
    "conan" ) cmd_conan $@ ;;
    "format" ) cmd_format $@ ;;
    "generate" ) cmd_generate $@ ;;
    "profiles" ) cmd_profiles $@ ;;
    "run" ) cmd_run $@ ;;
    "splash" ) cmd_splash $@ ;;
    "test" ) cmd_test $@ ;;
    "vcpkg" ) cmd_vcpkg $@ ;;
    * )
        echo "'${cmd}' is not a valid command."
        echo
        show_help
        exit 1
esac
